name: 'distribution'

on: push

jobs:
  test:
  	# job 이름 설정
    name: Test lint, tsc, build
    # 리눅스 환경에서 사용
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
		
      # 해당 환경을 Node.js 위에서 실행하겠다고 명시
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ secrets.NODE_VERSION }}
		
      # 모듈 변화가 있을 때만 npm install
      - name: Cache node modules
        uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install

      - run: npm run build
        if: ${{ always() }}
